name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v4

  deploy:
    runs-on: 'bpmn-statistic'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact.zip
