# The xml command in this script is using xmlstartlet(https://xmlstar.sourceforge.net)

name: Dev Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dev_build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
          overwrite-settings: false
      - name: Build maven
        id: build-maven
        run: |
          modules=("bpmn-statistic" "bpmn-statistic-demo")
          builtModules=()
          filesChange=$(git diff --name-only HEAD HEAD^)
          for module in ${modules[@]}
          do
            if [[ "$filesChange" =~ .*"$module".* ]]; then
              builtModules+=("$module")
              mvn clean install -f $module/pom.xml
            fi
          done
          echo BUILT_MODULES=${builtModules[@]} >> $GITHUB_OUTPUT
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bpmn-statistic-artifacts
          path: |
            */target/*.iar
