name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v4
    with:
      ivyVersion: nightly-10.0
      ivyPluginVersion: 10.0.16
      testerVersion: 10.0.16

  deploy:
    needs: build
    runs-on: 'bpmn-statistic'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Copy file
        run: |
          version=$(xml sel -t -m "//_:project" -v _:version pom.xml)
          artifactDir=artifact/bpmn-statistic
          engineDir=/var/tools/ivy/10/applications/BPMN-STATISTIC
          cp ${artifactDir}/target/bpmn-statistic-${version}.iar $engineDir/bpmn-statistic/1.iar
          cp ${artifactDir}-demo/target/bpmn-statistic-demo-${version}.iar $engineDir/bpmn-statistic-demo/1.iar

      - name: Remove artifact
        run: rm -rf artifact
